### ISSUE TITLE
I can’t add rust agent to my wasn?

### ISSUE THREAD

**Issue by aliscie** [dfinity/agent-rs#386] opened 2022-09-27 20:24 UTC
When I add 
```toml
[dependencies]
ic-agent = "0.20.0"
```
To `Cargo.toml` I got this error
```console
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.

error[E0583]: file not found for module `sys`
   --> /Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/lib.rs:124:1
    |
124 | mod sys;
    | ^^^^^^^^
    |
    = help: to create the module `sys`, create file "/Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/sys.rs" or "/Users/apple/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/sys/mod.rs"

```

I tride older versions but nothing

**Comment by adamspofford-dfinity** [comment] 2022-09-28 18:23
Correct. The agent is for client-side code (and for browsers, js-sys support has not been added yet). For canisters you would use `ic_cdk::call`, and for browsers you would use agent-js.

**Comment by aliscie** [comment] 2022-10-02 07:06
I tried using it but what is the `ArgumentEncoder`??
```rs
async move {
        let greeting = call(principal, "greet", ("Ali")).await.unwrap();
    };
```

# error
```rs
27  |         let greeting = call(principal, "greet", ("Ali")).await.unwrap();
    |                        ----                     ^^^^^^^ the trait `ArgumentEncoder` is not implemented for `&str`

```

**Comment by adamspofford-dfinity** [comment] 2022-12-01 23:25
Add a comma: `("Ali",)`

Otherwise `("Ali")` is the same thing as writing `"Ali"`.

**Comment by hafezrouzati** [comment] 2023-03-08 23:50
Wanted to clarify, does this mean that agent-rs won't work for a Rust application that's compiled to WASM and runs in the browser?

**Comment by adamspofford-dfinity** [comment] 2023-03-09 22:52
Correct. This is a feature in our backlog, but for now, if you wanted to interact with the IC from browser wasm, your best bet is agent-js through wasm_bindgen.

**Comment by adamspofford-dfinity** [comment] 2023-03-09 22:53
Closing as the stated issue is intended behavior.

**Closed by adamspofford-dfinity** 2023-03-09 22:53 UTC
